name: 'Add SSH Private key'
description: 'Connect your GitHub Action workflow to Tailscale'
branding:
  icon: 'arrow-right-circle'
  color: 'green'
inputs:
  private_key:
    description: 'SSH Private key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' && runner.os != 'macOS' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux and macOS Only"
        exit 1
    - name: Start SSH agent with a key
      shell: bash
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
        ssh-add - <<< "${{ inputs.private_key }}"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV  
